#ifndef WSCLEAN_VERSION_H
#define WSCLEAN_VERSION_H

#define WSCLEAN_VERSION_STR  "1.3"
#define WSCLEAN_VERSION_MAJOR 1
#define WSCLEAN_VERSION_MINOR 3
#define WSCLEAN_VERSION_DATE "2014-08-05"

#endif
