#ifndef WSCLEAN_VERSION_H
#define WSCLEAN_VERSION_H

#define WSCLEAN_VERSION_STR  "1.8"
#define WSCLEAN_VERSION_MAJOR 1
#define WSCLEAN_VERSION_MINOR 8
#define WSCLEAN_VERSION_DATE "2015-05-21"

#endif
